# -*- coding: utf-8 -*-
"""Q-Learning with Open AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1REfB-HLY1npeIxlNf4sWb_VCFcOm-JLI

**Part A: Explore a Gymnasium Environment**
"""

!pip install gymnasium

import gymnasium as gym

env = gym.make("FrozenLake-v1", render_mode="ansi")

observation, info = env.reset()

print("Initial Observation:", observation)
print("Info:", info)

for step in range(5):
    action = env.action_space.sample()

    observation, reward, terminated, truncated, info = env.step(action)

    done = terminated or truncated

    print(f"\nStep {step + 1}")
    print("Action Taken:", action)
    print("New Observation:", observation)
    print("Reward:", reward)
    print("Done:", done)
    print("Info:", info)

    if done:
        print("\nEpisode finished. Resetting environment...\n")
        observation, info = env.reset()

"""**Part B: Implement Q-Learning**"""

import gymnasium as gym
import numpy as np
import random

env = gym.make("FrozenLake-v1")

state_size = env.observation_space.n
action_size = env.action_space.n

q_table = np.zeros((state_size, action_size))

print("Q-table shape:", q_table.shape)
print(q_table)

alpha = 0.8
gamma = 0.95
epsilon = 1.0
epsilon_decay = 0.995
epsilon_min = 0.01
episodes = 2000
max_steps = 100

rewards_per_episode = []

for episode in range(episodes):
    state, info = env.reset()
    done = False
    total_rewards = 0

    for step in range(max_steps):

        if random.uniform(0, 1) < epsilon:
            action = env.action_space.sample()
        else:
            action = np.argmax(q_table[state])

        new_state, reward, terminated, truncated, info = env.step(action)
        done = terminated or truncated


        q_table[state, action] = q_table[state, action] + alpha * (
            reward + gamma * np.max(q_table[new_state]) - q_table[state, action]
        )

        state = new_state
        total_rewards += reward

        if done:
            break

    epsilon = max(epsilon_min, epsilon * epsilon_decay)

    rewards_per_episode.append(total_rewards)

print("Trained Q-table:")
print(q_table)

print("Average reward over all episodes:", np.mean(rewards_per_episode))
print("Total successes:", sum(rewards_per_episode))

"""**Part C: Evaluate and Visualize**"""

test_episodes = 100
max_steps = 100
successes = 0
total_rewards = []

for episode in range(test_episodes):
    state, info = env.reset()
    done = False
    episode_reward = 0

    for step in range(max_steps):

        action = np.argmax(q_table[state])

        new_state, reward, terminated, truncated, info = env.step(action)
        done = terminated or truncated

        state = new_state
        episode_reward += reward

        if done:
            break

    total_rewards.append(episode_reward)
    if episode_reward > 0:
        successes += 1

average_reward = np.mean(total_rewards)
success_rate = successes / test_episodes

print("Test Episodes:", test_episodes)
print("Average Reward:", average_reward)
print("Success Rate:", success_rate)

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 5))
plt.plot(rewards_per_episode)
plt.xlabel("Episode")
plt.ylabel("Total Reward")
plt.title("Total Reward per Episode")
plt.show()

window_size = 100
moving_avg = np.convolve(rewards_per_episode, np.ones(window_size)/window_size, mode='valid')

plt.figure(figsize=(10, 5))
plt.plot(moving_avg)
plt.xlabel("Episode")
plt.ylabel("Moving Average Reward")
plt.title("Moving Average of Rewards")
plt.show()

"""**Part D: Reflection**

*1) Challenges Encountered*

  One challenge I encountered was the randomness of the FrozenLake environment. Because the surface is slippery, the agent's actions do not always lead to the expected outcome, which made learning slower and less consistent. Early in training, the agent also struggled due to the exploration phase, where it takes many randome actions before learning useful patterns. Additionally, rewards are sparse (only given when reaching the goal), which makes it harder for the agent to learn quickly.


*2) Effect of Hyperparameters*

  Changing hyperparameters had a noticeable impact on learning:

  - Learning rate (alpha): A higher learning rate helped the agent learn faster, but sometimes cause unstable updates. A lower value made learning more stable but slower.
  - Discount factor (gamma): A higher gamma encouraged the agent to focus on long-term rewards, which is importanat in reaching the goal. A lower gamma made the agent more short-sighted.
  - Exploration rate (epsilon): Starting with a high epsilon allowed the agent to explore more, but if it stayed too high, the agent didn't learn effectively. Decaying epsilon over time helped balance exploration and exploitation.

*3) Real-World Applications*

Q-Learning and reinforcement learning can be applied in many real-world scenarios. For example, in sports analytics, it could be used to model decision-making, such as choosing optimal plays based on game situations. In autonomous driving, RL helps vehicles learn how to safely navigate by interacting with their environment. It is also used in recommendation systems, robotics, and game AI, where systems improve their performance over time through trial and error.
"""

